### ISSUE TITLE
querySelector no longer works correctly with comma separated selectors if first selector does not match

### ISSUE THREAD

**Issue by nrkn** [jsdom/jsdom#3666]
### Basic info:

- **Node.js version:** v20.11.0
- **jsdom version:** v23.2.0

### Minimal reproduction case

```js
import { JSDOM } from 'jsdom'

const html = `
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  </head>
  <body>
    <p>One</p>
    <span>Two</span>
  </body>
</html>
`

const dom = new JSDOM(html)

const { document } = dom.window

const pOrSpan = document.querySelector('p, span')

// correct - it's p
console.log( pOrSpan )

// fails if the first option doesn't exist!
const divOrSpan = document.querySelector('div, span')

// should be span - but it's null!
console.log( divOrSpan )

// however, this works
const spanOrDiv = document.querySelector('span, div')

console.log( spanOrDiv )

```

### How does similar code behave in browsers?

In browsers, it selects the second option if the first doesn't exist - and same for previous version of JSDOM

**Comment by asamuzaK** [comment]
Thanks for the catch.
Fixed upstream.

Please try again with the latest development build of dom-selector.

```console
npm i --save-dev @asamuzakjp/dom-selector@next
```

**Comment by nrkn** [comment]
Thanks, unfortunately I'm still getting null with the divOrSpan example above after installing latest dom-selector

**Comment by domenic** [comment]
This should work on main, and I think we will have good test coverage, so closing.
